"""
Dashboard Page - Visualizes the value generated by Scribe.
"""

import logging
from PyQt5.QtWidgets import QWidget, QVBoxLayout, QHBoxLayout, QLabel
from qfluentwidgets import (
    TitleLabel,
    CardWidget,
    BodyLabel,
    StrongBodyLabel
)

from scribe.analytics.value_calculator import ValueCalculator

logger = logging.getLogger(__name__)

class DashboardPage(QWidget):
    """A page to display key performance indicators and value metrics."""

    def __init__(self, value_calculator: ValueCalculator, parent=None):
        super().__init__(parent)
        self.setObjectName("DashboardPage")
        
        self.value_calculator = value_calculator
        
        main_layout = QVBoxLayout(self)
        main_layout.setContentsMargins(16, 12, 16, 12)
        main_layout.setSpacing(8)
        
        # Header
        title = TitleLabel("Dashboard")
        subtitle = BodyLabel("Quantifying your productivity gains with Scribe.")
        main_layout.addWidget(title)
        main_layout.addWidget(subtitle)
        
        # Main content
        self.kpi_layout = QHBoxLayout()
        main_layout.addLayout(self.kpi_layout)
        
        # Create KPI cards
        self.time_saved_card = self._create_kpi_card("Time Saved", "0h 0m")
        self.words_transcribed_card = self._create_kpi_card("Words Transcribed", "0")
        self.commands_executed_card = self._create_kpi_card("Commands Executed", "0")
        
        self.kpi_layout.addWidget(self.time_saved_card)
        self.kpi_layout.addWidget(self.words_transcribed_card)
        self.kpi_layout.addWidget(self.commands_executed_card)
        
        main_layout.addStretch()

        self.update_dashboard()

    def _create_kpi_card(self, title: str, value: str) -> CardWidget:
        """Create a card to display a key performance indicator."""
        card = CardWidget()
        layout = QVBoxLayout(card)
        
        title_label = StrongBodyLabel(title)
        value_label = TitleLabel(value)
        value_label.setObjectName("value_label")
        
        layout.addWidget(title_label)
        layout.addWidget(value_label)
        
        return card

    def update_dashboard(self):
        """Update the dashboard with the latest analytics."""
        summary = self.value_calculator.get_session_summary()
        
        # Update time saved card
        time_saved_label = self.time_saved_card.findChild(QLabel, "value_label")
        if time_saved_label:
            hours = int(summary.time_saved_vs_typing / 3600)
            minutes = int((summary.time_saved_vs_typing % 3600) / 60)
            time_saved_label.setText(f"{hours}h {minutes}m")
            
        # Update words transcribed card
        words_transcribed_label = self.words_transcribed_card.findChild(QLabel, "value_label")
        if words_transcribed_label:
            words_transcribed_label.setText(f"{summary.total_words:,}")
            
        # Update commands executed card
        commands_executed_label = self.commands_executed_card.findChild(QLabel, "value_label")
        if commands_executed_label:
            commands_executed_label.setText(str(summary.total_commands))

        logger.info("Dashboard updated with latest analytics.")